"""OSIS 命令流 STAGE 模块 — 施工阶段(激活/钝化、体系转换)"""

from __future__ import annotations

from pyosis import batch

from pyosis.core.engine import OSISEngine

def build_stages(engine: OSISEngine) -> None:
    # 创建施工阶段
    engine.stage.create(1, "下部结构施工", 60.0)
    # 通过单元组激活/钝化单元
    engine.stage.get(1).define_element(1, 1, "桥墩", 15.0, 0)
    # 通过边界组激活/钝化边界
    engine.stage.get(1).define_boundary(1, 1, "墩底固结")
    # 激活/钝化荷载工况
    engine.stage.get(1).define_loadcase(1, 1, "", "下部结构施工自重")
    engine.stage.create(2, "浇筑0号块", 15.0)
    engine.stage.get(2).define_element(1, 1, "块0", 7.0, 0)
    engine.stage.get(2).define_boundary(1, 1, "墩梁固结")
    engine.stage.get(2).define_loadcase(1, 1, "", "浇筑0号块自重")
    engine.stage.get(2).define_loadcase(1, 1, "", "中横梁_墩顶横梁")
    engine.stage.create(3, "张拉0号块", 1.0)
    engine.stage.get(3).define_loadcase(1, 1, "", "预应力_钢束0")
    engine.stage.create(4, "1号块挂篮安装", 15.0)
    engine.stage.get(4).define_loadcase(1, 1, "", "挂篮自重_挂篮1")
    engine.stage.create(5, "浇筑1号块", 7.0)
    engine.stage.get(5).define_element(1, 1, "块1", 7.0, 0)
    engine.stage.get(5).define_loadcase(1, 1, "", "浇筑1号块自重")
    engine.stage.create(6, "张拉1号块", 1.0)
    engine.stage.get(6).define_loadcase(1, 1, "", "预应力_钢束1")
    engine.stage.create(7, "2号块挂篮前移", 1.0)
    engine.stage.get(7).define_loadcase(1, 1, "", "挂篮自重_挂篮2")
    engine.stage.get(7).define_loadcase(1, 0, "", "挂篮自重_挂篮1")
    engine.stage.create(8, "浇筑2号块", 7.0)
    engine.stage.get(8).define_element(1, 1, "块2", 7.0, 0)
    engine.stage.get(8).define_loadcase(1, 1, "", "浇筑2号块自重")
    engine.stage.create(9, "张拉2号块", 1.0)
    engine.stage.get(9).define_loadcase(1, 1, "", "预应力_钢束2")
    engine.stage.create(10, "3号块挂篮前移", 1.0)
    engine.stage.get(10).define_loadcase(1, 1, "", "挂篮自重_挂篮3")
    engine.stage.get(10).define_loadcase(1, 0, "", "挂篮自重_挂篮2")
    engine.stage.create(11, "浇筑3号块", 7.0)
    engine.stage.get(11).define_element(1, 1, "块3", 7.0, 0)
    engine.stage.get(11).define_loadcase(1, 1, "", "浇筑3号块自重")
    engine.stage.create(12, "张拉3号块", 1.0)
    engine.stage.get(12).define_loadcase(1, 1, "", "预应力_钢束3")
    engine.stage.create(13, "4号块挂篮前移", 1.0)
    engine.stage.get(13).define_loadcase(1, 1, "", "挂篮自重_挂篮4")
    engine.stage.get(13).define_loadcase(1, 0, "", "挂篮自重_挂篮3")
    engine.stage.create(14, "浇筑4号块", 7.0)
    engine.stage.get(14).define_element(1, 1, "块4", 7.0, 0)
    engine.stage.get(14).define_loadcase(1, 1, "", "浇筑4号块自重")
    engine.stage.create(15, "张拉4号块", 1.0)
    engine.stage.get(15).define_loadcase(1, 1, "", "预应力_钢束4")
    engine.stage.create(16, "5号块挂篮前移", 1.0)
    engine.stage.get(16).define_loadcase(1, 1, "", "挂篮自重_挂篮5")
    engine.stage.get(16).define_loadcase(1, 0, "", "挂篮自重_挂篮4")
    engine.stage.create(17, "浇筑5号块", 7.0)
    engine.stage.get(17).define_element(1, 1, "块5", 7.0, 0)
    engine.stage.get(17).define_loadcase(1, 1, "", "浇筑5号块自重")
    engine.stage.create(18, "张拉5号块", 1.0)
    engine.stage.get(18).define_loadcase(1, 1, "", "预应力_钢束5")
    engine.stage.create(19, "6号块挂篮前移", 1.0)
    engine.stage.get(19).define_loadcase(1, 1, "", "挂篮自重_挂篮6")
    engine.stage.get(19).define_loadcase(1, 0, "", "挂篮自重_挂篮5")
    engine.stage.create(20, "浇筑6号块", 7.0)
    engine.stage.get(20).define_element(1, 1, "块6", 7.0, 0)
    engine.stage.get(20).define_loadcase(1, 1, "", "浇筑6号块自重")
    engine.stage.create(21, "张拉6号块", 1.0)
    engine.stage.get(21).define_loadcase(1, 1, "", "预应力_钢束6")
    engine.stage.create(22, "7号块挂篮前移", 1.0)
    engine.stage.get(22).define_loadcase(1, 1, "", "挂篮自重_挂篮7")
    engine.stage.get(22).define_loadcase(1, 0, "", "挂篮自重_挂篮6")
    engine.stage.create(23, "浇筑7号块", 7.0)
    engine.stage.get(23).define_element(1, 1, "块7", 7.0, 0)
    engine.stage.get(23).define_loadcase(1, 1, "", "浇筑7号块自重")
    engine.stage.create(24, "张拉7号块", 1.0)
    engine.stage.get(24).define_loadcase(1, 1, "", "预应力_钢束7")
    engine.stage.create(25, "8号块挂篮前移", 1.0)
    engine.stage.get(25).define_loadcase(1, 1, "", "挂篮自重_挂篮8")
    engine.stage.get(25).define_loadcase(1, 0, "", "挂篮自重_挂篮7")
    engine.stage.create(26, "浇筑8号块", 7.0)
    engine.stage.get(26).define_element(1, 1, "块8", 7.0, 0)
    engine.stage.get(26).define_loadcase(1, 1, "", "浇筑8号块自重")
    engine.stage.create(27, "张拉8号块", 1.0)
    engine.stage.get(27).define_loadcase(1, 1, "", "预应力_钢束8")
    engine.stage.create(28, "9号块挂篮前移", 1.0)
    engine.stage.get(28).define_loadcase(1, 1, "", "挂篮自重_挂篮9")
    engine.stage.get(28).define_loadcase(1, 0, "", "挂篮自重_挂篮8")
    engine.stage.create(29, "浇筑9号块", 7.0)
    engine.stage.get(29).define_element(1, 1, "块9", 7.0, 0)
    engine.stage.get(29).define_loadcase(1, 1, "", "浇筑9号块自重")
    engine.stage.create(30, "张拉9号块", 1.0)
    engine.stage.get(30).define_loadcase(1, 1, "", "预应力_钢束9")
    engine.stage.create(31, "10号块挂篮前移", 1.0)
    engine.stage.get(31).define_loadcase(1, 1, "", "挂篮自重_挂篮10")
    engine.stage.get(31).define_loadcase(1, 0, "", "挂篮自重_挂篮9")
    engine.stage.create(32, "浇筑10号块", 7.0)
    engine.stage.get(32).define_element(1, 1, "块10", 7.0, 0)
    engine.stage.get(32).define_loadcase(1, 1, "", "浇筑10号块自重")
    engine.stage.create(33, "张拉10号块", 1.0)
    engine.stage.get(33).define_loadcase(1, 1, "", "预应力_钢束10")
    engine.stage.create(34, "11号块挂篮前移", 1.0)
    engine.stage.get(34).define_loadcase(1, 1, "", "挂篮自重_挂篮11")
    engine.stage.get(34).define_loadcase(1, 0, "", "挂篮自重_挂篮10")
    engine.stage.create(35, "浇筑11号块", 7.0)
    engine.stage.get(35).define_element(1, 1, "块11", 7.0, 0)
    engine.stage.get(35).define_loadcase(1, 1, "", "浇筑11号块自重")
    engine.stage.create(36, "张拉11号块", 1.0)
    engine.stage.get(36).define_loadcase(1, 1, "", "预应力_钢束11")
    engine.stage.create(37, "12号块挂篮前移", 1.0)
    engine.stage.get(37).define_loadcase(1, 1, "", "挂篮自重_挂篮12")
    engine.stage.get(37).define_loadcase(1, 0, "", "挂篮自重_挂篮11")
    engine.stage.create(38, "浇筑12号块", 7.0)
    engine.stage.get(38).define_element(1, 1, "块12", 7.0, 0)
    engine.stage.get(38).define_loadcase(1, 1, "", "浇筑12号块自重")
    engine.stage.create(39, "张拉12号块", 1.0)
    engine.stage.get(39).define_loadcase(1, 1, "", "预应力_钢束12")
    engine.stage.create(40, "13号块挂篮前移", 1.0)
    engine.stage.get(40).define_loadcase(1, 1, "", "挂篮自重_挂篮13")
    engine.stage.get(40).define_loadcase(1, 0, "", "挂篮自重_挂篮12")
    engine.stage.create(41, "浇筑13号块", 7.0)
    engine.stage.get(41).define_element(1, 1, "块13", 7.0, 0)
    engine.stage.get(41).define_loadcase(1, 1, "", "浇筑13号块自重")
    engine.stage.create(42, "张拉13号块", 1.0)
    engine.stage.get(42).define_loadcase(1, 1, "", "预应力_钢束13")
    engine.stage.create(43, "14号块挂篮前移", 1.0)
    engine.stage.get(43).define_loadcase(1, 1, "", "挂篮自重_挂篮14")
    engine.stage.get(43).define_loadcase(1, 0, "", "挂篮自重_挂篮13")
    engine.stage.create(44, "浇筑14号块", 7.0)
    engine.stage.get(44).define_element(1, 1, "块14", 7.0, 0)
    engine.stage.get(44).define_loadcase(1, 1, "", "浇筑14号块自重")
    engine.stage.create(45, "张拉14号块", 1.0)
    engine.stage.get(45).define_loadcase(1, 1, "", "预应力_钢束14")
    engine.stage.create(46, "15号挂篮前移", 1.0)
    engine.stage.get(46).define_loadcase(1, 1, "", "挂篮自重_挂篮15")
    engine.stage.get(46).define_loadcase(1, 0, "", "挂篮自重_挂篮14")
    engine.stage.create(47, "浇筑15号块", 7.0)
    engine.stage.get(47).define_element(1, 1, "块15", 7.0, 0)
    engine.stage.get(47).define_loadcase(1, 1, "", "浇筑15号块自重")
    engine.stage.create(48, "张拉15号块", 1.0)
    engine.stage.get(48).define_loadcase(1, 1, "", "预应力_钢束15")
    engine.stage.create(49, "16号块挂篮前移", 1.0)
    engine.stage.get(49).define_loadcase(1, 1, "", "挂篮自重_挂篮16")
    engine.stage.get(49).define_loadcase(1, 0, "", "挂篮自重_挂篮15")
    engine.stage.create(50, "浇筑16号块", 7.0)
    engine.stage.get(50).define_element(1, 1, "块16", 7.0, 0)
    engine.stage.get(50).define_loadcase(1, 1, "", "浇筑16号块自重")
    engine.stage.create(51, "张拉16号块", 1.0)
    engine.stage.get(51).define_loadcase(1, 1, "", "预应力_钢束16")
    engine.stage.create(52, "17号块挂篮前移", 1.0)
    engine.stage.get(52).define_loadcase(1, 1, "", "挂篮自重_挂篮17")
    engine.stage.get(52).define_loadcase(1, 0, "", "挂篮自重_挂篮16")
    engine.stage.create(53, "浇筑17号块及边跨现浇段", 7.0)
    engine.stage.get(53).define_element(1, 1, "边跨现浇段", 7.0, 0)
    engine.stage.get(53).define_element(1, 1, "块17", 7.0, 0)
    engine.stage.get(53).define_boundary(1, 1, "边跨现浇段临时支架")
    engine.stage.get(53).define_loadcase(1, 1, "", "浇筑17号块及边跨现浇段自重")
    engine.stage.get(53).define_loadcase(1, 1, "", "边横梁_1_端横梁")
    engine.stage.get(53).define_loadcase(1, 1, "", "边横梁_2_端横梁")
    engine.stage.get(53).define_loadcase(1, 1, "", "边横梁_3_端横梁")
    engine.stage.get(53).define_loadcase(1, 1, "", "边横梁_4_端横梁")
    engine.stage.create(54, "张拉17号块", 1.0)
    engine.stage.get(54).define_loadcase(1, 1, "", "预应力_钢束17")
    engine.stage.create(55, "拆除挂篮，安装吊架", 15.0)
    engine.stage.get(55).define_loadcase(1, 1, "", "挂篮自重_边跨合拢吊架")
    engine.stage.get(55).define_loadcase(1, 1, "", "挂篮自重_中跨合拢吊架")
    engine.stage.get(55).define_loadcase(1, 0, "", "挂篮自重_挂篮17")
    engine.stage.create(56, "浇筑边跨合拢段", 7.0)
    engine.stage.get(56).define_element(1, 1, "边跨合拢段", 7.0, 0)
    engine.stage.get(56).define_boundary(1, 1, "边墩永久支座")
    engine.stage.get(56).define_boundary(1, 0, "边跨现浇段临时支架")
    engine.stage.get(56).define_loadcase(1, 1, "", "浇筑边跨合拢段自重")
    engine.stage.create(57, "张拉边跨合拢段钢束", 3.0)
    engine.stage.get(57).define_loadcase(1, 1, "", "预应力_边跨合拢束")
    engine.stage.create(58, "合拢顶推", 1.0)
    engine.stage.get(58).define_loadcase(1, 1, "", "合拢顶推力_顶推力")
    engine.stage.create(59, "浇筑中跨合拢段", 7.0)
    engine.stage.get(59).define_element(1, 1, "中跨合拢段", 7.0, 0)
    engine.stage.get(59).define_loadcase(1, 1, "", "浇筑中跨合拢段自重")
    engine.stage.get(59).define_loadcase(1, 1, "", "横隔板")
    engine.stage.create(60, "张拉中跨合拢段钢束", 3.0)
    engine.stage.get(60).define_loadcase(1, 0, "", "合拢顶推力_顶推力")
    engine.stage.get(60).define_loadcase(1, 1, "", "预应力_中跨合拢束")
    engine.stage.create(61, "拆除吊架", 2.0)
    engine.stage.get(61).define_loadcase(1, 0, "", "挂篮自重_边跨合拢吊架")
    engine.stage.get(61).define_loadcase(1, 0, "", "挂篮自重_中跨合拢吊架")
    engine.stage.create(62, "二期荷载", 60.0)
    engine.stage.get(62).define_loadcase(1, 1, "", "二期荷载_二期")
    engine.stage.create(63, "十年收缩徐变", 3650.0)
    engine.stage.create(64, "运营", 0.0)
    engine.stage.get(64).define_loadcase(1, 1, "", "整体升温")
    engine.stage.get(64).define_loadcase(1, 1, "", "整体降温")
    engine.stage.get(64).define_loadcase(1, 1, "", "温度梯度_升温_")
    engine.stage.get(64).define_loadcase(1, 1, "", "温度梯度_降温_")
    # 激活分析工况,分析工况默认在每个施工阶段的静力工况之后，不同分析工况无先后顺序
    engine.stage.get(64).define_analysis(1, "SETL", "支座沉降")
    engine.stage.get(64).define_analysis(1, "LIVE", "移动荷载")

if __name__ == "__main__":
    from _0_engine import engine
    with batch():
        build_stages(engine)
