"""OSIS 命令流 STAGE 模块 — 施工阶段(激活/钝化、体系转换)"""

from __future__ import annotations

from pyosis import batch

from pyosis.core.engine import OSISEngine

def build_stages(engine: OSISEngine) -> None:
    # 创建施工阶段
    engine.stage.create(1, "桥墩施工", 30.0)
    # 通过单元组激活/钝化单元
    engine.stage.get(1).define_element(1, 1, "桥墩", 7.0, 0)
    # 通过边界组激活/钝化边界
    engine.stage.get(1).define_boundary(1, 1, "墩底")
    # 激活/钝化荷载工况
    engine.stage.get(1).define_loadcase(1, 1, "", "桥墩施工自重")
    engine.stage.create(2, "浇筑0号块", 28.0)
    engine.stage.get(2).define_element(1, 1, "块0", 7.0, 0)
    engine.stage.get(2).define_boundary(1, 1, "墩梁固结")
    engine.stage.get(2).define_boundary(1, 1, "主墩临时固结")
    engine.stage.get(2).define_loadcase(1, 1, "", "浇筑0号块自重")
    engine.stage.get(2).define_loadcase(1, 1, "", "横隔板_墩顶横隔板")
    engine.stage.create(3, "挂篮1", 3.0)
    engine.stage.get(3).define_loadcase(1, 1, "", "挂篮_挂篮1")
    engine.stage.create(4, "浇筑1号块", 7.0)
    engine.stage.get(4).define_element(1, 1, "块1", 7.0, 0)
    engine.stage.get(4).define_loadcase(1, 1, "", "浇筑1号块自重")
    engine.stage.create(5, "张拉1", 3.0)
    engine.stage.get(5).define_loadcase(1, 1, "", "预应力_张拉1")
    engine.stage.create(6, "挂篮2", 3.0)
    engine.stage.get(6).define_loadcase(1, 1, "", "挂篮_挂篮2")
    engine.stage.get(6).define_loadcase(1, 0, "", "挂篮_挂篮1")
    engine.stage.create(7, "浇筑2号块", 7.0)
    engine.stage.get(7).define_element(1, 1, "块2", 7.0, 0)
    engine.stage.get(7).define_loadcase(1, 1, "", "浇筑2号块自重")
    engine.stage.create(8, "张拉2", 3.0)
    engine.stage.get(8).define_loadcase(1, 1, "", "预应力_张拉2")
    engine.stage.create(9, "挂篮3", 3.0)
    engine.stage.get(9).define_loadcase(1, 1, "", "挂篮_挂篮3")
    engine.stage.get(9).define_loadcase(1, 0, "", "挂篮_挂篮2")
    engine.stage.create(10, "浇筑3号块", 7.0)
    engine.stage.get(10).define_element(1, 1, "块3", 7.0, 0)
    engine.stage.get(10).define_loadcase(1, 1, "", "浇筑3号块自重")
    engine.stage.create(11, "张拉3", 3.0)
    engine.stage.get(11).define_loadcase(1, 1, "", "预应力_张拉3")
    engine.stage.create(12, "挂篮4", 3.0)
    engine.stage.get(12).define_loadcase(1, 1, "", "挂篮_挂篮4")
    engine.stage.get(12).define_loadcase(1, 0, "", "挂篮_挂篮3")
    engine.stage.create(13, "浇筑4号块", 7.0)
    engine.stage.get(13).define_element(1, 1, "块4", 7.0, 0)
    engine.stage.get(13).define_loadcase(1, 1, "", "浇筑4号块自重")
    engine.stage.create(14, "张拉4", 3.0)
    engine.stage.get(14).define_loadcase(1, 1, "", "预应力_张拉4")
    engine.stage.create(15, "挂篮5", 3.0)
    engine.stage.get(15).define_loadcase(1, 1, "", "挂篮_挂篮5")
    engine.stage.get(15).define_loadcase(1, 0, "", "挂篮_挂篮4")
    engine.stage.create(16, "浇筑5号块", 7.0)
    engine.stage.get(16).define_element(1, 1, "块5", 7.0, 0)
    engine.stage.get(16).define_loadcase(1, 1, "", "浇筑5号块自重")
    engine.stage.get(16).define_loadcase(1, 1, "", "齿块_5号块齿块")
    engine.stage.create(17, "张拉5", 3.0)
    engine.stage.get(17).define_loadcase(1, 1, "", "预应力_张拉5")
    engine.stage.create(18, "挂篮6", 3.0)
    engine.stage.get(18).define_loadcase(1, 1, "", "挂篮_挂篮6")
    engine.stage.get(18).define_loadcase(1, 0, "", "挂篮_挂篮5")
    engine.stage.create(19, "浇筑6号块", 7.0)
    engine.stage.get(19).define_element(1, 1, "块6", 7.0, 0)
    engine.stage.get(19).define_loadcase(1, 1, "", "浇筑6号块自重")
    engine.stage.get(19).define_loadcase(1, 1, "", "齿块_6号块齿块")
    engine.stage.create(20, "张拉6", 3.0)
    engine.stage.get(20).define_loadcase(1, 1, "", "预应力_张拉6")
    engine.stage.create(21, "挂篮7", 3.0)
    engine.stage.get(21).define_loadcase(1, 1, "", "挂篮_挂篮7")
    engine.stage.get(21).define_loadcase(1, 0, "", "挂篮_挂篮6")
    engine.stage.create(22, "浇筑7号块", 7.0)
    engine.stage.get(22).define_element(1, 1, "块7", 7.0, 0)
    engine.stage.get(22).define_loadcase(1, 1, "", "浇筑7号块自重")
    engine.stage.get(22).define_loadcase(1, 1, "", "齿块_7号块齿块")
    engine.stage.create(23, "张拉7", 3.0)
    engine.stage.get(23).define_loadcase(1, 1, "", "预应力_张拉7")
    engine.stage.create(24, "挂篮8", 3.0)
    engine.stage.get(24).define_loadcase(1, 1, "", "挂篮_挂篮8")
    engine.stage.get(24).define_loadcase(1, 0, "", "挂篮_挂篮7")
    engine.stage.create(25, "浇筑8号块", 7.0)
    engine.stage.get(25).define_element(1, 1, "块8", 7.0, 0)
    engine.stage.get(25).define_loadcase(1, 1, "", "浇筑8号块自重")
    engine.stage.get(25).define_loadcase(1, 1, "", "齿块_边跨8号块齿块")
    engine.stage.get(25).define_loadcase(1, 1, "", "齿块_中跨8号块齿块")
    engine.stage.create(26, "张拉8", 3.0)
    engine.stage.get(26).define_loadcase(1, 1, "", "预应力_张拉8")
    engine.stage.create(27, "挂篮9", 3.0)
    engine.stage.get(27).define_loadcase(1, 1, "", "挂篮_挂篮9")
    engine.stage.get(27).define_loadcase(1, 0, "", "挂篮_挂篮8")
    engine.stage.create(28, "浇筑9号块", 7.0)
    engine.stage.get(28).define_element(1, 1, "块9", 7.0, 0)
    engine.stage.get(28).define_loadcase(1, 1, "", "浇筑9号块自重")
    engine.stage.get(28).define_loadcase(1, 1, "", "齿块_边跨9号块齿块")
    engine.stage.get(28).define_loadcase(1, 1, "", "齿块_中跨9号块齿块")
    engine.stage.create(29, "张拉9", 3.0)
    engine.stage.get(29).define_loadcase(1, 1, "", "预应力_张拉9")
    engine.stage.create(30, "挂篮10", 3.0)
    engine.stage.get(30).define_loadcase(1, 1, "", "挂篮_挂篮10")
    engine.stage.get(30).define_loadcase(1, 0, "", "挂篮_挂篮9")
    engine.stage.create(31, "浇筑10号块", 7.0)
    engine.stage.get(31).define_element(1, 1, "块10", 7.0, 0)
    engine.stage.get(31).define_loadcase(1, 1, "", "浇筑10号块自重")
    engine.stage.get(31).define_loadcase(1, 1, "", "齿块_10号块齿块")
    engine.stage.create(32, "张拉10", 3.0)
    engine.stage.get(32).define_loadcase(1, 1, "", "预应力_张拉10")
    engine.stage.create(33, "挂篮11", 3.0)
    engine.stage.get(33).define_loadcase(1, 1, "", "挂篮_挂篮11")
    engine.stage.get(33).define_loadcase(1, 0, "", "挂篮_挂篮10")
    engine.stage.create(34, "浇筑11号块", 7.0)
    engine.stage.get(34).define_element(1, 1, "块11", 7.0, 0)
    engine.stage.get(34).define_loadcase(1, 1, "", "浇筑11号块自重")
    engine.stage.get(34).define_loadcase(1, 1, "", "齿块_中跨11号块齿块")
    engine.stage.get(34).define_loadcase(1, 1, "", "齿块_边跨11号块齿块")
    engine.stage.create(35, "张拉11", 3.0)
    engine.stage.get(35).define_loadcase(1, 1, "", "预应力_张拉11")
    engine.stage.create(36, "挂篮12", 3.0)
    engine.stage.get(36).define_loadcase(1, 1, "", "挂篮_挂篮12")
    engine.stage.get(36).define_loadcase(1, 0, "", "挂篮_挂篮11")
    engine.stage.create(37, "浇筑12号块", 7.0)
    engine.stage.get(37).define_element(1, 1, "块12", 7.0, 0)
    engine.stage.get(37).define_loadcase(1, 1, "", "浇筑12号块自重")
    engine.stage.get(37).define_loadcase(1, 1, "", "齿块_边跨12号块齿块")
    engine.stage.get(37).define_loadcase(1, 1, "", "齿块_中跨12号块齿块")
    engine.stage.create(38, "张拉12", 3.0)
    engine.stage.get(38).define_loadcase(1, 1, "", "预应力_张拉12")
    engine.stage.create(39, "挂篮13", 3.0)
    engine.stage.get(39).define_loadcase(1, 1, "", "挂篮_挂篮13")
    engine.stage.get(39).define_loadcase(1, 0, "", "挂篮_挂篮12")
    engine.stage.create(40, "浇筑13号块", 7.0)
    engine.stage.get(40).define_element(1, 1, "块13", 7.0, 0)
    engine.stage.get(40).define_loadcase(1, 1, "", "浇筑13号块自重")
    engine.stage.get(40).define_loadcase(1, 1, "", "齿块_边跨13号梁齿块")
    engine.stage.get(40).define_loadcase(1, 1, "", "齿块_中跨13号块齿块")
    engine.stage.create(41, "张拉13", 3.0)
    engine.stage.get(41).define_loadcase(1, 1, "", "预应力_张拉13")
    engine.stage.create(42, "边跨现浇段", 7.0)
    engine.stage.get(42).define_element(1, 1, "现浇直线段", 7.0, 0)
    engine.stage.get(42).define_boundary(1, 1, "边跨现浇临时支架")
    engine.stage.get(42).define_loadcase(1, 1, "", "边跨现浇段自重")
    engine.stage.get(42).define_loadcase(1, 1, "", "横隔板_边跨横隔板")
    engine.stage.create(43, "边跨合龙吊篮", 3.0)
    engine.stage.get(43).define_loadcase(1, 1, "", "挂篮_边跨合龙挂篮")
    engine.stage.get(43).define_loadcase(1, 0, "", "挂篮_挂篮13")
    engine.stage.create(44, "浇筑边跨合龙段", 7.0)
    engine.stage.get(44).define_element(1, 1, "边跨合龙段", 7.0, 0)
    engine.stage.get(44).define_boundary(1, 1, "边跨现浇段")
    engine.stage.get(44).define_boundary(1, 0, "边跨现浇临时支架")
    engine.stage.get(44).define_loadcase(1, 1, "", "浇筑边跨合龙段自重")
    engine.stage.create(45, "张拉边跨底板，合龙束", 3.0)
    engine.stage.get(45).define_loadcase(1, 0, "", "挂篮_边跨合龙挂篮")
    engine.stage.get(45).define_loadcase(1, 1, "", "预应力_边跨合龙钢束")
    engine.stage.get(45).define_loadcase(1, 1, "", "预应力_边跨底板束")
    engine.stage.create(46, "1，5中跨吊篮", 3.0)
    engine.stage.get(46).define_loadcase(1, 1, "", "挂篮_1，5中跨合龙挂篮")
    engine.stage.create(47, "浇筑1，5合龙段", 7.0)
    engine.stage.get(47).define_element(1, 1, "中跨合龙段1", 7.0, 0)
    engine.stage.get(47).define_element(1, 1, "中跨合龙段5", 7.0, 0)
    engine.stage.get(47).define_loadcase(1, 1, "", "浇筑1，5合龙段自重")
    engine.stage.create(48, "张拉1，5中跨合龙束及底板束", 3.0)
    engine.stage.get(48).define_loadcase(1, 0, "", "挂篮_3合龙挂篮")
    engine.stage.get(48).define_loadcase(1, 0, "", "挂篮_1，5中跨合龙挂篮")
    engine.stage.get(48).define_loadcase(1, 1, "", "预应力_\"1")
    engine.stage.create(49, "顶推2，4", 1.0)
    engine.stage.get(49).define_loadcase(1, 1, "", "顶推_2，4顶推")
    engine.stage.create(50, "2，4吊篮", 2.0)
    engine.stage.get(50).define_loadcase(1, 1, "", "挂篮_2，4合龙挂篮")
    engine.stage.get(50).define_loadcase(1, 0, "", "挂篮_1，5中跨合龙挂篮")
    engine.stage.create(51, "浇筑2，4中跨合龙段", 7.0)
    engine.stage.get(51).define_element(1, 1, "中跨合龙段2", 7.0, 0)
    engine.stage.get(51).define_element(1, 1, "中跨合龙段4", 7.0, 0)
    engine.stage.get(51).define_loadcase(1, 1, "", "浇筑2，4中跨合龙段自重")
    engine.stage.create(52, "张拉2，4中跨底板束及合龙束", 3.0)
    engine.stage.get(52).define_loadcase(1, 1, "", "预应力_\"2")
    engine.stage.create(53, "3中跨吊篮", 3.0)
    engine.stage.get(53).define_loadcase(1, 1, "", "挂篮_3合龙挂篮")
    engine.stage.get(53).define_loadcase(1, 0, "", "挂篮_2，4合龙挂篮")
    engine.stage.create(54, "浇筑3中跨合龙段", 7.0)
    engine.stage.get(54).define_element(1, 1, "中跨合龙段3", 7.0, 0)
    engine.stage.get(54).define_loadcase(1, 1, "", "浇筑3中跨合龙段自重")
    engine.stage.create(55, "张拉3中跨合龙束及底板束", 2.0)
    engine.stage.get(55).define_loadcase(1, 1, "", "预应力_3中跨底板束")
    engine.stage.create(56, "体系转换", 3.0)
    engine.stage.get(56).define_element(1, 1, "边主墩支座", 0.0, 0)
    engine.stage.get(56).define_boundary(1, 1, "边主墩支座")
    engine.stage.get(56).define_boundary(1, 0, "主墩临时固结")
    engine.stage.get(56).define_loadcase(1, 0, "", "挂篮_3合龙挂篮")
    engine.stage.create(57, "二期", 30.0)
    engine.stage.get(57).define_loadcase(1, 1, "", "二期_-6.3m")
    engine.stage.get(57).define_loadcase(1, 1, "", "二期_6.3m")
    engine.stage.create(58, "十年收缩徐变", 3650.0)
    engine.stage.create(59, "运营", 0.0)
    engine.stage.get(59).define_loadcase(1, 1, "", "整体升温")
    engine.stage.get(59).define_loadcase(1, 1, "", "整体降温")
    engine.stage.get(59).define_loadcase(1, 1, "", "正温度梯度")
    engine.stage.get(59).define_loadcase(1, 1, "", "负温度梯度")
    engine.stage.get(59).define_loadcase(1, 1, "", "制动力")
    # 激活分析工况,分析工况默认在每个施工阶段的静力工况之后，不同分析工况无先后顺序
    engine.stage.get(59).define_analysis(1, "MODAL", "")
    engine.stage.get(59).define_analysis(1, "SETL", "支座沉降")
    engine.stage.get(59).define_analysis(1, "LIVE", "汽车荷载")

if __name__ == "__main__":
    from _0_engine import engine
    with batch():
        build_stages(engine)
