"""OSIS 命令流 BOUNDARY 模块 — 边界条件(支座、约束自由度)"""

from __future__ import annotations

from pyosis import batch

from pyosis.core.engine import OSISEngine

def build_boundaries(engine: OSISEngine) -> None:
    # 创建边界（便捷入口，内部转发到对应 create_* 方法）
    engine.boundary.create(1, "GENERAL", "", 1, 0, 1, 0, 0, 0, 0)
    # 分配边界给节点
    engine.boundary.get(1).assign("a", 205, 423)
    engine.boundary.create(2, "GENERAL", "", 1, 1, 1, 0, 0, 0, 0)
    engine.boundary.get(2).assign("a", 204, 422)
    engine.boundary.create(3, "GENERAL", "", 0, 0, 1, 0, 0, 0, 0)
    engine.boundary.get(3).assign("a", 1, "3to6", "198to201", 203)
    engine.boundary.create(4, "GENERAL", "", 0, 0, 1, 0, 0, 0, 0)
    engine.boundary.get(4).assign("a", 205, 423)
    engine.boundary.create(5, "GENERAL", "", 0, 1, 1, 0, 0, 0, 0)
    engine.boundary.get(5).assign("a", 204, 422)
    engine.boundary.create(6, "GENERAL", "", 1, 1, 1, 1, 1, 1, 0)
    engine.boundary.get(6).assign("a", 253, 271, 290, 309, 328, 347, 366, 385, 439, 457)
    engine.boundary.create(7, "MSTSLV", 22, 1, 1, 1, 1, 1, 1, 0)
    engine.boundary.get(7).assign("a", "458to459")
    engine.boundary.create(8, "MSTSLV", 182, 1, 1, 1, 1, 1, 1, 0)
    engine.boundary.get(8).assign("a", "462to463")
    engine.boundary.create(9, "RIGID", 202)
    engine.boundary.get(9).assign("a", 423)
    engine.boundary.create(10, "RIGID", 202)
    engine.boundary.get(10).assign("a", 422)
    engine.boundary.create(11, "RIGID", 202)
    engine.boundary.get(11).assign("a", 423)
    engine.boundary.create(12, "RIGID", 202)
    engine.boundary.get(12).assign("a", 422)
    engine.boundary.create(13, "RIGID", 2)
    engine.boundary.get(13).assign("a", 205)
    engine.boundary.create(14, "RIGID", 2)
    engine.boundary.get(14).assign("a", 204)
    engine.boundary.create(15, "RIGID", 53)
    engine.boundary.get(15).assign("a", 236)
    engine.boundary.create(16, "RIGID", 55)
    engine.boundary.get(16).assign("a", 254)
    engine.boundary.create(17, "RIGID", 85)
    engine.boundary.get(17).assign("a", 272)
    engine.boundary.create(18, "RIGID", 87)
    engine.boundary.get(18).assign("a", 291)
    engine.boundary.create(19, "RIGID", 117)
    engine.boundary.get(19).assign("a", 310)
    engine.boundary.create(20, "RIGID", 119)
    engine.boundary.get(20).assign("a", 329)
    engine.boundary.create(21, "RIGID", 149)
    engine.boundary.get(21).assign("a", 348)
    engine.boundary.create(22, "RIGID", 151)
    engine.boundary.get(22).assign("a", 367)
    engine.boundary.create(23, "RIGID", 22)
    engine.boundary.get(23).assign("a", 425)
    engine.boundary.create(24, "RIGID", 182)
    engine.boundary.get(24).assign("a", 441)
    engine.boundary.create(25, "RIGID", 461)
    engine.boundary.get(25).assign("a", 425)
    engine.boundary.create(26, "RIGID", 460)
    engine.boundary.get(26).assign("a", 425)
    engine.boundary.create(27, "RIGID", 465)
    engine.boundary.get(27).assign("a", 441)
    engine.boundary.create(28, "RIGID", 464)
    engine.boundary.get(28).assign("a", 441)
    engine.boundary.create(29, "RIGID", 202)
    engine.boundary.get(29).assign("a", 423)
    engine.boundary.create(30, "RIGID", 202)
    engine.boundary.get(30).assign("a", 422)
    engine.boundary.create(31, "RIGID", 2)
    engine.boundary.get(31).assign("a", 205)
    engine.boundary.create(32, "RIGID", 2)
    engine.boundary.get(32).assign("a", 204)
    # 创建边界组并返回刷新后的对象
    engine.boundary.group.create("边跨现浇段", "c")
    engine.boundary.group.create("边跨现浇段", "a", "4to5", "9to14")
    engine.boundary.group.create("边跨现浇临时支架", "c")
    engine.boundary.group.create("边跨现浇临时支架", "a", "1to3", "29to32")
    engine.boundary.group.create("边主墩支座", "c")
    engine.boundary.group.create("边主墩支座", "a", "7to8", "25to28")
    engine.boundary.group.create("墩底", "c")
    engine.boundary.group.create("墩底", "a", 6)
    engine.boundary.group.create("墩梁固结", "c")
    engine.boundary.group.create("墩梁固结", "a", "15to22")
    engine.boundary.group.create("主墩临时固结", "c")
    engine.boundary.group.create("主墩临时固结", "a", "23to24")

if __name__ == "__main__":
    from _0_engine import engine
    with batch():
        build_boundaries(engine)
