"""OSIS 命令流 STAGE 模块 — 施工阶段(激活/钝化、体系转换)"""

from __future__ import annotations

from pyosis import batch

from pyosis.core.engine import OSISEngine

def build_stages(engine: OSISEngine) -> None:
    # 创建施工阶段
    engine.stage.create(1, "CS1_0号段施工", 28.0)
    # 通过单元组激活/钝化单元
    engine.stage.get(1).define_element(1, 1, "0号块单元", 28.0, 0)
    # 通过边界组激活/钝化边界
    engine.stage.get(1).define_boundary(1, 1, "桥墩1临时支架")
    engine.stage.get(1).define_boundary(1, 1, "桥墩2临时支架")
    # 激活/钝化荷载工况
    engine.stage.get(1).define_loadcase(1, 1, "", "0号块单元自重")
    engine.stage.get(1).define_loadcase(1, 1, "", "0号块预应力")
    engine.stage.create(2, "CS2_1号段挂篮", 1.0)
    engine.stage.get(2).define_loadcase(1, 1, "", "挂篮荷载1")
    engine.stage.create(3, "CS3_1号段浇筑", 8.0)
    engine.stage.get(3).define_loadcase(1, 1, "", "湿重1")
    engine.stage.create(4, "CS4_1号段预应力", 1.0)
    engine.stage.get(4).define_element(1, 1, "1号块单元", 7.0, 0)
    engine.stage.get(4).define_loadcase(1, 1, "", "1号块单元自重")
    engine.stage.get(4).define_loadcase(1, 0, "", "湿重1")
    engine.stage.get(4).define_loadcase(1, 1, "", "1号块预应力")
    engine.stage.create(5, "CS5_2号段挂篮", 1.0)
    engine.stage.get(5).define_loadcase(1, 1, "", "挂篮荷载2")
    engine.stage.get(5).define_loadcase(1, 0, "", "挂篮荷载1")
    engine.stage.create(6, "CS6_2号段浇筑", 8.0)
    engine.stage.get(6).define_loadcase(1, 1, "", "湿重2")
    engine.stage.create(7, "CS7_2号段预应力", 1.0)
    engine.stage.get(7).define_element(1, 1, "2号块单元", 7.0, 0)
    engine.stage.get(7).define_loadcase(1, 1, "", "2号块单元自重")
    engine.stage.get(7).define_loadcase(1, 0, "", "湿重2")
    engine.stage.get(7).define_loadcase(1, 1, "", "2号块预应力")
    engine.stage.create(8, "CS8_3号段挂篮", 1.0)
    engine.stage.get(8).define_loadcase(1, 1, "", "挂篮荷载3")
    engine.stage.get(8).define_loadcase(1, 0, "", "挂篮荷载2")
    engine.stage.create(9, "CS9_3号段浇筑", 8.0)
    engine.stage.get(9).define_loadcase(1, 1, "", "湿重3")
    engine.stage.create(10, "CS10_3号段预应力", 1.0)
    engine.stage.get(10).define_element(1, 1, "3号块单元", 7.0, 0)
    engine.stage.get(10).define_loadcase(1, 1, "", "3号块单元自重")
    engine.stage.get(10).define_loadcase(1, 0, "", "湿重3")
    engine.stage.get(10).define_loadcase(1, 1, "", "3号块预应力")
    engine.stage.create(11, "CS11_4号段挂篮", 1.0)
    engine.stage.get(11).define_loadcase(1, 1, "", "挂篮荷载4")
    engine.stage.get(11).define_loadcase(1, 0, "", "挂篮荷载3")
    engine.stage.create(12, "CS12_4号段浇筑", 8.0)
    engine.stage.get(12).define_loadcase(1, 1, "", "湿重4")
    engine.stage.create(13, "CS13_4号段预应力", 1.0)
    engine.stage.get(13).define_element(1, 1, "4号块单元", 7.0, 0)
    engine.stage.get(13).define_loadcase(1, 1, "", "4号块单元自重")
    engine.stage.get(13).define_loadcase(1, 0, "", "湿重4")
    engine.stage.get(13).define_loadcase(1, 1, "", "4号块预应力")
    engine.stage.create(14, "CS14_5号段挂篮", 1.0)
    engine.stage.get(14).define_loadcase(1, 1, "", "挂篮荷载5")
    engine.stage.get(14).define_loadcase(1, 0, "", "挂篮荷载4")
    engine.stage.create(15, "CS15_5号段浇筑", 8.0)
    engine.stage.get(15).define_loadcase(1, 1, "", "湿重5")
    engine.stage.create(16, "CS16_5号段预应力", 1.0)
    engine.stage.get(16).define_element(1, 1, "5号块单元", 7.0, 0)
    engine.stage.get(16).define_loadcase(1, 1, "", "5号块单元自重")
    engine.stage.get(16).define_loadcase(1, 0, "", "湿重5")
    engine.stage.get(16).define_loadcase(1, 1, "", "5号块预应力")
    engine.stage.create(17, "CS17_边跨支架现浇", 12.0)
    engine.stage.get(17).define_element(1, 1, "边跨现浇段", 7.0, 0)
    engine.stage.get(17).define_boundary(1, 1, "右边跨临时支架")
    engine.stage.get(17).define_boundary(1, 1, "左边跨临时支架")
    engine.stage.get(17).define_loadcase(1, 1, "", "边跨现浇段自重")
    engine.stage.get(17).define_loadcase(1, 0, "", "挂篮荷载5")
    engine.stage.get(17).define_loadcase(1, 1, "", "左边跨合龙湿重")
    engine.stage.get(17).define_loadcase(1, 1, "", "左边跨合龙吊架荷载")
    engine.stage.get(17).define_loadcase(1, 1, "", "右边跨合龙湿重")
    engine.stage.get(17).define_loadcase(1, 1, "", "右边跨合龙吊架荷载")
    engine.stage.create(18, "CS18_左边跨、右边跨合龙", 12.0)
    engine.stage.get(18).define_element(1, 1, "弹簧单元_桥台1_顶底", 0.0, 0)
    engine.stage.get(18).define_element(1, 1, "弹簧单元_桥台2_顶底", 0.0, 0)
    engine.stage.get(18).define_element(1, 1, "右边跨合龙段", 7.0, 0)
    engine.stage.get(18).define_element(1, 1, "左边跨合龙段", 7.0, 0)
    engine.stage.get(18).define_boundary(1, 1, "桥台1_横向固定_纵向释放支座")
    engine.stage.get(18).define_boundary(1, 1, "桥台1_横向释放_纵向释放支座")
    engine.stage.get(18).define_boundary(1, 1, "桥台2_横向固定_纵向释放支座")
    engine.stage.get(18).define_boundary(1, 1, "桥台2_横向释放_纵向释放支座")
    engine.stage.get(18).define_boundary(1, 0, "右边跨临时支架")
    engine.stage.get(18).define_boundary(1, 0, "左边跨临时支架")
    engine.stage.get(18).define_loadcase(1, 1, "", "左边跨、右边跨合龙自重")
    engine.stage.get(18).define_loadcase(1, 0, "", "左边跨合龙吊架荷载")
    engine.stage.get(18).define_loadcase(1, 0, "", "左边跨合龙湿重")
    engine.stage.get(18).define_loadcase(1, 1, "", "左边跨预应力")
    engine.stage.get(18).define_loadcase(1, 0, "", "右边跨合龙吊架荷载")
    engine.stage.get(18).define_loadcase(1, 0, "", "右边跨合龙湿重")
    engine.stage.get(18).define_loadcase(1, 1, "", "右边跨预应力")
    engine.stage.get(18).define_loadcase(1, 1, "", "中跨1合龙湿重")
    engine.stage.get(18).define_loadcase(1, 1, "", "中跨1合龙吊架荷载")
    engine.stage.create(19, "CS19_中跨1合龙", 12.0)
    engine.stage.get(19).define_element(1, 1, "中跨1合龙段", 7.0, 0)
    engine.stage.get(19).define_loadcase(1, 1, "", "中跨1合龙自重")
    engine.stage.get(19).define_loadcase(1, 0, "", "中跨1合龙吊架荷载")
    engine.stage.get(19).define_loadcase(1, 0, "", "中跨1合龙湿重")
    engine.stage.get(19).define_loadcase(1, 1, "", "中跨1预应力")
    engine.stage.create(20, "CS20_体系转换", 15.0)
    engine.stage.get(20).define_element(1, 1, "弹簧单元_桥墩1_顶底", 0.0, 0)
    engine.stage.get(20).define_element(1, 1, "弹簧单元_桥墩2_顶底", 0.0, 0)
    engine.stage.get(20).define_boundary(1, 1, "桥墩1_横向固定_纵向固定支座")
    engine.stage.get(20).define_boundary(1, 1, "桥墩1_横向释放_纵向固定支座")
    engine.stage.get(20).define_boundary(1, 1, "桥墩2_横向固定_纵向释放支座")
    engine.stage.get(20).define_boundary(1, 1, "桥墩2_横向释放_纵向释放支座")
    engine.stage.get(20).define_boundary(1, 0, "桥墩1临时支架")
    engine.stage.get(20).define_boundary(1, 0, "桥墩2临时支架")
    engine.stage.create(21, "CS21_二期恒载", 60.0)
    engine.stage.get(21).define_loadcase(1, 1, "", "防撞护栏左")
    engine.stage.get(21).define_loadcase(1, 1, "", "防撞护栏右")
    engine.stage.get(21).define_loadcase(1, 1, "", "铺装左")
    engine.stage.get(21).define_loadcase(1, 1, "", "铺装右")
    engine.stage.create(22, "CS22_徐变十年", 3650.0)
    engine.stage.create(23, "CS23_运营阶段", 0.0)
    engine.stage.get(23).define_loadcase(1, 1, "", "整体升温")
    engine.stage.get(23).define_loadcase(1, 1, "", "整体降温")
    engine.stage.get(23).define_loadcase(1, 1, "", "正温度梯度")
    engine.stage.get(23).define_loadcase(1, 1, "", "负温度梯度")
    # 激活分析工况,分析工况默认在每个施工阶段的静力工况之后，不同分析工况无先后顺序
    engine.stage.get(23).define_analysis(1, "SETL", "沉降")
    engine.stage.get(23).define_analysis(1, "LIVE", "左偏载工况")
    engine.stage.get(23).define_analysis(1, "LIVE", "中载工况")
    engine.stage.get(23).define_analysis(1, "LIVE", "右偏载工况")

if __name__ == "__main__":
    from _0_engine import engine
    with batch():
        build_stages(engine)
